[package]
name = "giacomo_comprimi"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "^0.29.1"  # Mantieni questa versione
egui = "^0.29.1"    # Assicurati che la versione di egui sia la stessa di eframe
